const fse = require('fs-extra');
const glob = require('glob');
const path = require('path');

const BARREL_EXCLUDE = new Set(['AttachmentEdit', 'CodeModal', 'PreviewAttachment', 'tracking']);

const root = process.cwd();

const ENV_AGNOSTIC_ROOT = `${root}/src`;

function getModuleName(file) {
  return file.replace('/index.ts', '').split('/').pop();
}

function filterBarrelFiles(files) {
  return files.filter((file) => !BARREL_EXCLUDE.has(getModuleName(file)));
}

async function generateIndex(files, destRoot = ENV_AGNOSTIC_ROOT) {
  fse.ensureDirSync(path.resolve(destRoot));

  const destFile = `${destRoot}/index.ts`;

  const stream = fse.createWriteStream(destFile);

  return new Promise((resolve, reject) => {
    stream.once('open', () => {
      stream.write('// this file is autogenerated by generate-index.js, modifying it manually will have no effect\n');

      files.forEach((file) => {
        const name = getModuleName(file);

        if (BARREL_EXCLUDE.has(name)) {
          return;
        }

        stream.write(`\nexport { default as ${name} } from './${name}';\n`);
        stream.write(`export * from './${name}';\n`);
      });
      stream.end();
    });
    stream.once('close', resolve);
    stream.once('error', reject);
  });
}

async function run(files) {
  try {
    await generateIndex(filterBarrelFiles(files));
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exit(1);
  }
}

if (require.main === module) {
  const sourceFiles = glob.sync(path.resolve(__dirname, './src/*/index.ts'));
  run(sourceFiles);
}

module.exports = {
  BARREL_EXCLUDE,
  getModuleName,
  filterBarrelFiles,
  generateIndex
};
